## NumPy Basics
   #### Computer Vision Winter Semester 2020/2021 by Clemens Spielvogel
    
   NumPy is an open-source library for handling arrays with an arbitrary number of dimensions. It is commonly used in scientific computing and is used by most scientific python libraries. 
    
Why using NumPy arrays over python lists:
   * Memory efficiency
   * Speed
   * Offer additional functionalities
   
Installation (Ubuntu)
   * $ pip install numpy
   
Resources:
   * NumPy documentation: https://docs.scipy.org/doc/numpy-1.16.0/index.html
   * NumPy cheat sheet: https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf

### Importing

In [1]:
# Importing the library, usually as the alias np
import numpy as np

# Output the modules version
print(np.__version__)

1.18.5


### Creating NumPy arrays

In [2]:
# Creating a numpy array
array = np.array([1, 2, 3])

print(array)

[1 2 3]


In [3]:
# Numpy arrays can have an arbitrary number of dimensions
array2d = np.array([[1, 2, 3], [4, 5, 6]])

array3d = np.array([
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]])

print("2D:\n", array2d)
print("3D:\n", array3d)

2D:
 [[1 2 3]
 [4 5 6]]
3D:
 [[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


In [4]:
# Retrieving number of dimensions
print(".ndim")
print(array.ndim)
print(array2d.ndim)
print(array3d.ndim, "\n")

# Retrieving number of elements per dimension
print(".shape")
print(array.shape)
print(array2d.shape)
print(array3d.shape, "\n")

# Len() can be used but only shows the outermost number of elements
print("len()")
print(len(array))
print(len(array2d))
print(len(array3d), "\n")

.ndim
1
2
3 

.shape
(3,)
(2, 3)
(3, 2, 1) 

len()
3
2
3 



In [5]:
# Creating arrays can be done in several ways

# Casting from lists (also works for nested lists)
python_list = [4, 5, 6]
python_array = np.array(python_list)

print(type(python_list))
print(type(python_array))
print("Array cast from list:", python_array)

# Initializing with zeros or ones
zero_array = np.zeros((2, 2))
ones_array = np.ones((2, 2))

print("Array initialized with zeros:\n", zero_array)
print("Array initialized with ones:\n", ones_array)

# Initializing array with random numbers
random_array = np.random.random((2, 2))

print("Array initialized with random values:\n", random_array)

<class 'list'>
<class 'numpy.ndarray'>
Array cast from list: [4 5 6]
Array initialized with zeros:
 [[0. 0.]
 [0. 0.]]
Array initialized with ones:
 [[1. 1.]
 [1. 1.]]
Array initialized with random values:
 [[0.38180336 0.54771891]
 [0.68811085 0.26459297]]


In [6]:
# All (sub-) arrays along an axis must have the same length, otherwise they will be converted to lists
nested_list = np.array([[1,2,3], [4,5]])
print("Lower right empty:\n", nested_list)

array = np.array([[1, 2, 3], [4, 5, np.nan]])
print("Lower right filled:\n", array)

array = np.array([[1, 2, 3], [4, 5, 0]])
print("Lower right filled:\n", array)

Lower right empty:
 [list([1, 2, 3]) list([4, 5])]
Lower right filled:
 [[ 1.  2.  3.]
 [ 4.  5. nan]]
Lower right filled:
 [[1 2 3]
 [4 5 0]]


### Input / Output

In [7]:
# Saving array to disk in NPY (.npy) format
np.save("array", array)

# Validating storage
import os
print("Saved 'array.npy':", "array.npy" in os.listdir())

# Loading array
array_loaded = np.load("array.npy")
print(array_loaded)

# Remove array from disk
os.remove("array.npy")

Saved 'array.npy': True
[[1 2 3]
 [4 5 0]]


### Indexing

In [8]:
# Indexing is similar to python list indexing
first_element = array[0]
last_element = array[-1]
array_without_first_element = array[1:]

print("Original:", array)
print("First element:", first_element)
print("Last element:", last_element)
print("Array without first element:", array_without_first_element)

Original: [[1 2 3]
 [4 5 0]]
First element: [1 2 3]
Last element: [4 5 0]
Array without first element: [[4 5 0]]


In [9]:
# Same works for multi dimensional arrays
upper_right_element = array2d[0][-1]
lower_left_element = array2d[-1][0]

print("Original:\n", array2d)
print("Upper right element:", upper_right_element)
print("Lower left element:", lower_left_element)

Original:
 [[1 2 3]
 [4 5 6]]
Upper right element: 3
Lower left element: 4


In [10]:
# Elements in arrays can be exchanged by indexing
array1d = np.array([1, 2, 3])
print(array1d)
array1d[1] = 4
print(array1d)

# If several elements are contained at indexed position, all are exchanged
print(array)
array[0] = 10
print(array)

[1 2 3]
[1 4 3]
[[1 2 3]
 [4 5 0]]
[[10 10 10]
 [ 4  5  0]]


In [11]:
# Boolean masking
array = np.array([[0.1, 0, 0, 0, 0.3], [0, 0.1, 0, 0.9, 0.7]])
mask = (array > 0)

print("Original:\n", array)
print("Mask:\n", mask)
print("Mask applied to original:\n", array[mask])

Original:
 [[0.1 0.  0.  0.  0.3]
 [0.  0.1 0.  0.9 0.7]]
Mask:
 [[ True False False False  True]
 [False  True False  True  True]]
Mask applied to original:
 [0.1 0.3 0.1 0.9 0.7]


### Datatypes

In [12]:
# Use default datatype
array = np.array([1, 2, 3])
print("Default :", array.dtype)

array = np.array([1.0, 2.0, 3.0])
print("Default:", array.dtype)

# Specify a particular datatype on initialization
array = np.array([1, 2, 3], dtype=np.float16) # Alternatively, you can use dtype="float16"
print("Forced at initialization:", array.dtype)

# Specify a particular datatype after initialization
array = array.astype(np.float32)
print("Forced after initialization:", array.dtype)

Default : int64
Default: float64
Forced at initialization: float16
Forced after initialization: float32


### Array Math

In [13]:
# Arithmetic

array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])

print("Array 1:", array1)
print("Array 2:", array2)

# Elementwise addition (subtraction, division, multiplication with -, /, * respectively)
addition = array1 + array2
print("Added:", addition)

# Elementwise multiplication
multiplication = array1 * array2
print("Multiplied:", multiplication)

# Matrix multiplication
matrix_mul = array1.dot(array2)
print("Matrix multiplied:", matrix_mul)

# Square root
array1_sqrt = np.sqrt(array1)
print("Square root of array 1:", array1_sqrt)

# Exponentials
array1_exp = np.power(array1, 3)
print("Array 1 with exponent 3:", array1_exp)

Array 1: [1 2 3 4]
Array 2: [5 6 7 8]
Added: [ 6  8 10 12]
Multiplied: [ 5 12 21 32]
Matrix multiplied: 70
Square root of array 1: [1.         1.41421356 1.73205081 2.        ]
Array 1 with exponent 3: [ 1  8 27 64]


In [14]:
# Manipulation

array = np.array([[1,2,3], [4,5,6]])
print("Original:\n", array)

# Transposition
transposed = np.transpose(array)
print("Transposed:\n", transposed)

# Flatten array
flat = np.ravel(array)
print("Flattened:", flat)

# Reshaping array
reshaped = np.reshape(array, (3,2))
print("Reshaped:\n", reshaped)

Original:
 [[1 2 3]
 [4 5 6]]
Transposed:
 [[1 4]
 [2 5]
 [3 6]]
Flattened: [1 2 3 4 5 6]
Reshaped:
 [[1 2]
 [3 4]
 [5 6]]


### Other useful functionalities

In [15]:
# Retrieving unique elements
uniques = np.unique(array)

print("Original:\n", array)
print("Unique elements:", uniques)

# Counting unique elements
counts = np.unique(array, return_counts=True)
counts_dict = dict(zip(counts[0], counts[1]))

print("Counts as two arrays: ", counts)
print("Counts as dictionary:", counts_dict)

Original:
 [[1 2 3]
 [4 5 6]]
Unique elements: [1 2 3 4 5 6]
Counts as two arrays:  (array([1, 2, 3, 4, 5, 6]), array([1, 1, 1, 1, 1, 1]))
Counts as dictionary: {1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1}


In [16]:
# Rounding elements
array = np.array([1.11, 5.55, 9.99])
array_rounded = np.round(array, 1)

print(array_rounded)

[ 1.1  5.6 10. ]


In [17]:
print("Original:", array)

# Sum
print("Sum", array.sum())

# Arithmetic mean
print("Mean:", array.mean())

# Min / Max
print("Min:", array.min())
print("Max:", array.max())

Original: [1.11 5.55 9.99]
Sum 16.65
Mean: 5.55
Min: 1.11
Max: 9.99


In [18]:
# Stacking arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

stacked = np.stack([array1, array2], axis=1)

print(stacked)

[[1 4]
 [2 5]
 [3 6]]
